/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package org.example.app

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class MessageUtilsTest {
    @Test
    fun testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage())
    }

    @Test
    fun testBinarySearch() {
        val array = intArrayOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        assertEquals(4, binarySearchs(array, 5))
    }
}
