[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["Manchi L. <84918340+man-chi@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
